### PR TITLE
Prevent CachedConfluentSchemaRegistry from caching the 'latest' version.

### PR DESCRIPTION
**Pull request by damncabbage**
Fixes the problem with long-running code that uses CachedConfluentSchemaRegistry and:
- Initialises an `Avro::Messaging`,  
  calls `Messaging#fetch_schema(subject: 'my-example-value', version 'latest')`,  
  which calls `CachedConfluentSchemaRegistry#subject_version(subject, version)`, then
- Later, does another `fetch_schema(subject: 'my-example-value', version: 'latest')`,  
  … and gets back the same schema, even if it's changed since.

This shortcuts the process when the special `'latest'` version is asked for, never asking the cache to look up or store the result.

(Fixes https://github.com/dasch/avro_turf/issues/130; I opted not to spread the 'latest' version string into the cache code itself, which isn't currently aware of it.)

### CODE REVIEW

**Review by dasch — APPROVED** [review]
Thanks!

**Comment by dasch** [comment]
Actually, it seems like you've made this PR against your own fork. Can you create a PR against the original repo? Otherwise I won't be able to merge.

**Comment by damncabbage** [comment]
> Actually, it seems like you've made this PR against your own fork. Can you create a PR against the original repo? Otherwise I won't be able to merge.

@dasch Oh boy, I'm really sorry. I'll follow up now with another PR. 😅

**Comment by damncabbage** [comment]
Closed in favour of https://github.com/dasch/avro_turf/pull/140. (Oops.)

**Pull request closed without merging**
